### ISSUE TITLE
Web Backend Directory structure?

### ISSUE THREAD

**Issue by Eggonomicon** [TeamNT/CRACKEDFTNTLaunch#1]
Any chance you could upload a sample web backend directory structure?

I've compiled the launcher, and had it working for 1.6.4 however the web directory changed and I'm unable to figure out the new structure.

Eggonomicon

**Comment by Farossco** [comment]
What do you mean with "new structure", what version do you talk of ?

**Comment by Eggonomicon** [comment]
1.4.5 the current version on the FTBLauncher Github site.

ie on my fileserver I have 
FTB2/modpacks/modpackname/modpackversion/modpack.zip
FTB2/static/various xml files (ie modpacks.xml, maps.xml etc
FTB2/msjsons/versions/1.7.10/1.7.10.json

FTB2/maven/net/ftb/launcher/beta/launcher-beta.json

md5/FTB2/modpacks/modpackname/modpackversion/modpack.zip (which is a file containing my md5 checksum)

The modpack shows up in my build of the launcher from my website with my details and images, however it will not download. When I click the download button I get the following:

[14:47:03] [ERROR] in Launcher ArrayList.elementData:-1->Main$8.uncaughtException:401: Unhandled exception in Thread[AWT-EventQueue-0,6,main]: java.lang.ArrayIndexOutOfBoundsException: -1
java.util.ArrayList.elementData(Unknown Source)
java.util.ArrayList.get(Unknown Source)
net.ftb.data.ModPack.getPack(ModPack.java:140)
net.ftb.data.ModPack.getSelectedPack(ModPack.java:173)
net.ftb.gui.LaunchFrame.doLaunch(LaunchFrame.java:907)
net.ftb.gui.LaunchFrame$6.actionPerformed(LaunchFrame.java:251)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$300(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)

and I am stumped. I'm missing something with the web back end directory structure.

Any help would be greatly appreciated!

Pastebin link of console: http://pastebin.com/tukxuYn3

**Comment by Farossco** [comment]
Yes, I know that problem, I will send you the sample tomorrow if I don't forget :)

**Comment by Eggonomicon** [comment]
That would be excellent!

Many thanks, I've been beating my self up over this since last night and haven't slept much. hehe

Eggonomicon

**Comment by Farossco** [comment]
And please, could you send me some screenshots of your launcher ?

**Comment by Eggonomicon** [comment]
Link to github Repository for my current changes: https://github.com/TheMinecraftian/FTBLaunch

![launcher](https://cloud.githubusercontent.com/assets/6493684/6088616/9ce72b38-ae15-11e4-8ef3-6717fe0dd82c.png)

![launcher_console](https://cloud.githubusercontent.com/assets/6493684/6088618/a40b5f6a-ae15-11e4-9fd8-2f33317acb2a.png)

Eggonomicon

Edit Note: Only The Witch Craftian modpack is actually there, the other 3 are just for reference, and are only in the xml file and not on the webbackend.

**Comment by Eggonomicon** [comment]
Not trying to be a pain, just a gentle reminder if you get a chance =D

Eggo

On Fri, Feb 6, 2015 at 3:01 PM, Farès Chati notifications@github.com
wrote:

> And please, could you send me some screenshots of your launcher ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TeamNT/CRACKEDFTNTLaunch/issues/1#issuecomment-73320731
> .

## 

Proud member of The Minecraftian community
www.theminecraftian.com

**Comment by Farossco** [comment]
Hum... I'm quit busy theses day and I'm sorry but I'll try to do it as fat as I can.

**Comment by Farossco** [comment]
A free gift:

https://mega.co.nz/#!X5ACkIaa!wn8fLPcm7fGFur_Ha8McLYs85ysvl2md-nMEP_S1D-E

**Comment by Farossco** [comment]
For the maven and msjson folders, I made a redirection by .htaccess, it is in the sample, tell me if you still have trouble

**Comment by Eggonomicon** [comment]
You sir are a life saver!

I did not have the map folder, but I believe it was the .htaccess file that
did the trick. It is working like a charm! I never thought of using an
.htaccess file for the maven and msjson folders, that's genius!

Many thanks!

Eggonomicon

On Sun, Feb 8, 2015 at 12:17 PM, Farès Chati notifications@github.com
wrote:

> For the maven and msjson folders, I made a redirection by .htaccess, it is
> in the sample, tell me if you still have trouble
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TeamNT/CRACKEDFTNTLaunch/issues/1#issuecomment-73426332
> .

## 

Proud member of The Minecraftian community
www.theminecraftian.com

**Comment by Farossco** [comment]
You're welcome friend :)
